"""initial schema

Revision ID: 5b39f3205e4d
Revises: 
Create Date: 2026-08-22 17:37:35.641141
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5b39f3205e4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_tags_kind_slug', ['kind', 'slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('pricing_url', sa.String(length=500), nullable=True),
    sa.Column('docs_url', sa.String(length=500), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('pricing_status', sa.String(length=30), nullable=False),
    sa.Column('free_access_summary', sa.Text(), nullable=True),
    sa.Column('pricing_summary', sa.Text(), nullable=True),
    sa.Column('best_for', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('not_ideal_for', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_open_source', sa.Boolean(), nullable=False),
    sa.Column('has_api', sa.Boolean(), nullable=False),
    sa.Column('has_free_api', sa.Boolean(), nullable=False),
    sa.Column('has_mcp', sa.Boolean(), nullable=False),
    sa.Column('has_agent', sa.Boolean(), nullable=False),
    sa.Column('has_local_model', sa.Boolean(), nullable=False),
    sa.Column('self_hostable', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_source_url', sa.String(length=500), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index('ix_tools_active_created', ['is_active', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_featured'), ['featured'], unique=False)
        batch_op.create_index('ix_tools_featured_pricing', ['featured', 'pricing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_last_verified_at'), ['last_verified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_pricing_status'), ['pricing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_slug'), ['slug'], unique=True)

    op.create_table('collection_tools',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_tools_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_collection_tools_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'tool_id', name=op.f('pk_collection_tools'))
    )
    with op.batch_alter_table('collection_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_tools_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_tools_tool_id'), ['tool_id'], unique=False)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_favorites_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_client_id'), ['client_id'], unique=False)
        batch_op.create_index('ix_favorites_client_tool', ['client_id', 'tool_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_favorites_tool_id'), ['tool_id'], unique=False)

    op.create_table('free_access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('period', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('restrictions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requires_credit_card', sa.Boolean(), nullable=True),
    sa.Column('expires', sa.Boolean(), nullable=True),
    sa.Column('expires_after_days', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_free_access_grants_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_free_access_grants'))
    )
    with op.batch_alter_table('free_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_access_grants_tool_id'), ['tool_id'], unique=False)

    op.create_table('pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('is_per_seat', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_pricing_plans_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_plans'))
    )
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_plans_tool_id'), ['tool_id'], unique=False)

    op.create_table('tool_categories',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_tool_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_categories_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'category_id', name=op.f('pk_tool_categories'))
    )
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_categories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_categories_tool_id'), ['tool_id'], unique=False)

    op.create_table('tool_tags',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tool_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_tool_tags_tool_id_tools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'tag_id', name=op.f('pk_tool_tags'))
    )
    with op.batch_alter_table('tool_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_tags_tool_id'), ['tool_id'], unique=False)

    # ### end Alembic commands ###

    # PostgreSQL only: GIN index backing the full-text search path in
    # ToolRepository. SQLite falls back to the portable LIKE scorer.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_tools_search_tsv ON tools "
            "USING GIN (to_tsvector('english', search_text))"
        )
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX ix_tools_name_trgm ON tools "
            "USING GIN (name gin_trgm_ops)"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_tools_name_trgm")
        op.execute("DROP INDEX IF EXISTS ix_tools_search_tsv")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_tags_tool_id'))
        batch_op.drop_index(batch_op.f('ix_tool_tags_tag_id'))

    op.drop_table('tool_tags')
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_categories_tool_id'))
        batch_op.drop_index(batch_op.f('ix_tool_categories_category_id'))

    op.drop_table('tool_categories')
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_plans_tool_id'))

    op.drop_table('pricing_plans')
    with op.batch_alter_table('free_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_access_grants_tool_id'))

    op.drop_table('free_access_grants')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_tool_id'))
        batch_op.drop_index('ix_favorites_client_tool')
        batch_op.drop_index(batch_op.f('ix_favorites_client_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('collection_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_tools_tool_id'))
        batch_op.drop_index(batch_op.f('ix_collection_tools_collection_id'))

    op.drop_table('collection_tools')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_slug'))
        batch_op.drop_index(batch_op.f('ix_tools_pricing_status'))
        batch_op.drop_index(batch_op.f('ix_tools_name'))
        batch_op.drop_index(batch_op.f('ix_tools_last_verified_at'))
        batch_op.drop_index('ix_tools_featured_pricing')
        batch_op.drop_index(batch_op.f('ix_tools_featured'))
        batch_op.drop_index('ix_tools_active_created')

    op.drop_table('tools')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))
        batch_op.drop_index('ix_tags_kind_slug')
        batch_op.drop_index(batch_op.f('ix_tags_kind'))

    op.drop_table('tags')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_slug'))

    op.drop_table('collections')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    # ### end Alembic commands ###
